### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by mikemhenry** [EBjerrum/scikit-mol#47]
I've added scikit-mol to conda-forge, @EBjerrum do you want to be included as a maintainer?

**Comment by EBjerrum** [comment]
Yes please, I think that would be wise

**Comment by mikemhenry** [comment]
Done! https://github.com/conda-forge/scikit-mol-feedstock

**Comment by mikemhenry** [comment]
this issue should trigger the bot to add you as a maintainer 
https://github.com/conda-forge/scikit-mol-feedstock/issues/1

**Comment by EBjerrum** [comment]
How can I see if I have been added as a maintainer?

**Comment by mikemhenry** [comment]
Hmm, it looks like the bot didn't add you, normally you show up here:
https://github.com/conda-forge/scikit-mol-feedstock/blob/main/recipe/meta.yaml#L46

I did see that you made a new tag and the bot picked it up:
https://github.com/conda-forge/scikit-mol-feedstock/pull/2

Looking at the diff:
https://github.com/EBjerrum/scikit-mol/compare/v0.4.1...v0.4.2

It doesn't look like any dependencies changed, so we won't need to do anything other than merge it.

I will modify the PR the bot made and add you as a maintainer. I will update here when that is done :)

**Comment by EBjerrum** [comment]
Got an invite for the repository and have accepted. I now appears to be added on the link you provided :-) Thanks for the help.
