### ISSUE TITLE
Incorrect description in tutorial 04

### ISSUE THREAD

**Issue by FDUguchunhui** [EBjerrum/scikit-mol#52]
![image](https://github.com/user-attachments/assets/19b12f87-a062-4d99-95d7-994b41ecaed4)

in "As we can see, the predictions with the standardizer and without are different. The two first molecules were benzoic acid and sodium benzoate, which with the standardized pipeline is predicted as the same, but differently with the nonstandardized pipeline.".

But in output, the ones without standardization are the same, and the ones with standardization are different
 ```
Predictions with no standardization: [0.51983795 0.51983795 2.06562022 3.01206795 3.95446692 4.92816899]
Predictions with standardization:    [0.51983795 0.61543701 2.31738354 3.01206795 3.44085399 4.37516731]
```

This can be fixed by changing
```
print(f'Predictions with no standardization: {std_pipe.predict(smiles_strings)}')
print(f'Predictions with standardization:    {nonstd_pipe.predict(smiles_strings)}')
```

to 

```
print(f'Predictions with standardization: {std_pipe.predict(smiles_strings)}')
print(f'Predictions with no standardization:    {nonstd_pipe.predict(smiles_strings)}')
```

The same goes with 
```
nonstd_pipe.fit(smiles_strings, fake_y)
print(f'Predictions with no standardization: {std_pipe.predict(smiles_strings)}')
print(f'Predictions with standardization:    {nonstd_pipe.predict(smiles_strings)}')
```
Change to 

```
nonstd_pipe.fit(smiles_strings, fake_y)
print(f'Predictions with standardization: {std_pipe.predict(smiles_strings)}')
print(f'Predictions with no standardization:    {nonstd_pipe.predict(smiles_strings)}')
```

**Comment by EBjerrum** [comment]
Ah, thanks, the predictions were swapped! Thanks for noting, I'll fix it when I get around to it, or you want to make a pull request? There's a script in the notebooks folder to sync the .py and ipynb via jupytext.

**Comment by FDUguchunhui** [comment]
Hi EBjerrum. Thank you for your invitation. But since it is a very minor change, you can easily fix it and no need to opn an pull request.

**Comment by EBjerrum** [comment]
Updated, will be in main soon
